name: Deploy prod
on:
  push:
    branches:
      - main
jobs:
  sync-s3-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd site || exit 1
          aws s3 sync ./ s3://mjw.sh/ --acl public-read